[package]
name = "embassy-net-wiznet"
version = "0.3.0"
edition = "2024"

[features]
defmt = [
    "dep:defmt",
    "embassy-net-driver-channel/defmt",
]

[dependencies]
defmt = { version = "1.0.1", optional = true }
embassy-futures = "0.1.2"
embassy-net-driver-channel = "0.4.0"
embassy-time = "0.5.1"
embedded-hal = "1.0"
embedded-hal-async = "1.0"
